name: az-sandbox
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - azure-storage-blob
  - jupyterlab
  - black
  - flake8
  - pyyaml
  - pandas
  - pre-commit
  - azure-identity
  - azure-storage-file
  - faker
  - python-dotenv
  - pip:
      - dvc[azure]==2.9.3
      - azure-ai-formrecognizer==3.1.2
